# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0002_hotels_industries_libraries_malls_museums_parks_restaurants_zoos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industries',
            old_name='industry_name',
            new_name='name',
        ),
    ]
