# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0003_auto_20171028_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='industries',
            old_name='industry_type',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='parks',
            old_name='park_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zoos',
            old_name='zoo_name',
            new_name='name',
        ),
    ]
