# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0004_auto_20171028_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='college_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='libraries',
            old_name='library_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='malls',
            old_name='mall_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='museums',
            old_name='museum_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
