# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0005_auto_20171028_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='Lat',
            field=models.IntegerField(default=-27.4772),
        ),
        migrations.AddField(
            model_name='colleges',
            name='Lon',
            field=models.IntegerField(default=153.0278),
        ),
    ]
