# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0008_auto_20171030_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='Lat',
            field=models.CharField(default=-27.4772, max_length=30),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='Lon',
            field=models.CharField(default=153.0278, max_length=30),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='Lat',
            field=models.CharField(default=-27.4772, max_length=30),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='Lon',
            field=models.CharField(default=153.0278, max_length=30),
        ),
    ]
