# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0013_auto_20171030_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='industries',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='industries',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='malls',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='malls',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='museums',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='museums',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='parks',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='parks',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
        migrations.AlterField(
            model_name='zoos',
            name='Lat',
            field=models.CharField(default='-27.4772', max_length=30),
        ),
        migrations.AlterField(
            model_name='zoos',
            name='Lon',
            field=models.CharField(default='153.0278', max_length=30),
        ),
    ]
