# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Tourist'), (3, 'Businessperson')], default=1),
        ),
    ]
